### ISSUE TITLE
C -> python

### ISSUE THREAD

**Issue by siniseong** [Attendance-check/JJick-check-Hardware#3]
``` import time
import board
import busio
from digitalio import DigitalInOut
from adafruit_pn532.spi import PN532_SPI

SCK = board.SCLK
MISO = board.MISO
MOSI = board.MOSI
CS = DigitalInOut(board.D5)

spi = busio.SPI(SCK, MOSI, MISO)
pn532 = PN532_SPI(spi, CS, debug=False)

print("Waiting for an NFC card...")

while True:
    try:
        uid = pn532.read_passive_target(timeout=0.5)
        if uid is not None:
            print("Found NFC card with UID:", [hex(i) for i in uid])
            time.sleep(1)
    except KeyboardInterrupt:
        break
```

**Comment by siniseong** [comment]
ubuntu@ubuntu:~/home/pi/mywebapp$ python3 hardware.py
Traceback (most recent call last):
  File "/home/ubuntu/home/pi/mywebapp/hardware.py", line 13, in <module>
    pn532 = PN532_SPI(spi, CS, debug=False)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/adafruit_pn532/spi.py", line 103, in __init__
    super().__init__(debug=debug, irq=irq, reset=reset)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/adafruit_pn532/adafruit_pn532.py", line 175, in __init__
    _ = self.firmware_version
  File "/home/ubuntu/.local/lib/python3.10/site-packages/adafruit_pn532/adafruit_pn532.py", line 362, in firmware_version
    raise RuntimeError("Failed to detect the PN532")
RuntimeError: Failed to detect the PN532

**Comment by siniseong** [comment]
ubuntu@ubuntu:~/home/pi/mywebapp$ sudo python3 hardware.py
Traceback (most recent call last):
  File "/home/ubuntu/home/pi/mywebapp/hardware.py", line 2, in <module>
    import board
ModuleNotFoundError: No module named 'board'

**Comment by siniseong** [comment]
```import time
import RPi.GPIO as GPIO
import busio
from digitalio import DigitalInOut
from adafruit_pn532.spi import PN532_SPI

SCK = GPIO.SCLK
MISO = GPIO.MISO
MOSI = GPIO.MOSI
CS = DigitalInOut(GPIO.D5)

spi = busio.SPI(SCK, MOSI, MISO)
pn532 = PN532_SPI(spi, CS, debug=False)

print("Waiting for an NFC card...")

while True:
    try:
        uid = pn532.read_passive_target(timeout=0.5)
        if uid is not None:
            print("Found NFC card with UID:", [hex(i) for i in uid])
            time.sleep(1)
    except KeyboardInterrupt:
        break
```

**Comment by siniseong** [comment]
ubuntu@ubuntu:~/home/pi/mywebapp$ sudo python3 hardware.py
Traceback (most recent call last):
  File "/home/ubuntu/home/pi/mywebapp/hardware.py", line 2, in <module>
    import busio
ModuleNotFoundError: No module named 'busio'

**Comment by siniseong** [comment]
``` import time
import RPi.GPIO as GPIO
import busio
from digitalio import DigitalInOut
from adafruit_pn532.spi import PN532_SPI

GPIO.setmode(GPIO.BCM)  # BCM 핀 번호 사용
SCK = GPIO.SCLK
MISO = GPIO.MISO
MOSI = GPIO.MOSI
CS = DigitalInOut(GPIO.D5)

spi = busio.SPI(SCK, MOSI, MISO)
pn532 = PN532_SPI(spi, CS, debug=False)

print("Waiting for an NFC card...")

while True:
    try:
        uid = pn532.read_passive_target(timeout=0.5)
        if uid is not None:
            print("Found NFC card with UID:", [hex(i) for i in uid])
            time.sleep(1)
    except KeyboardInterrupt:
        break
```

**Comment by siniseong** [comment]
ubuntu@ubuntu:~/home/pi/mywebapp$ sudo python3 hardware.py
Traceback (most recent call last):
  File "/home/ubuntu/home/pi/mywebapp/hardware.py", line 2, in <module>
    import busio
ModuleNotFoundError: No module named 'busio'

**Comment by siniseong** [comment]
``` import time
import RPi.GPIO as GPIO
from digitalio import DigitalInOut
from adafruit_pn532.spi import PN532_SPI

GPIO.setmode(GPIO.BCM)  # BCM 핀 번호 사용
SCK = GPIO.SCLK
MISO = GPIO.MISO
MOSI = GPIO.MOSI
CS = DigitalInOut(GPIO.D5)

pn532 = PN532_SPI(SCK, MOSI, MISO, CS, debug=False)

print("Waiting for an NFC card...")

while True:
    try:
        uid = pn532.read_passive_target(timeout=0.5)
        if uid is not None:
            print("Found NFC card with UID:", [hex(i) for i in uid])
            time.sleep(1)
    except KeyboardInterrupt:
        break
```

**Comment by siniseong** [comment]
ubuntu@ubuntu:~/home/pi/mywebapp$ sudo python3 hardware.py
Traceback (most recent call last):
  File "/home/ubuntu/home/pi/mywebapp/hardware.py", line 2, in <module>
    from digitalio import DigitalInOut
ModuleNotFoundError: No module named 'digitalio'

**Comment by siniseong** [comment]
``` import time
import RPi.GPIO as GPIO
from adafruit_pn532 import PN532_SPI

GPIO.setmode(GPIO.BCM)

# 원하는 핀 번호로 변경하세요
SCK = 11
MISO = 9
MOSI = 10
CS = 8

pn532 = PN532_SPI(spi_bus=0, spi_device=0, cs=CS, sclk=SCK, miso=MISO, mosi=MOSI, debug=False)

print("Waiting for an NFC card...")

while True:
    try:
        uid = pn532.read_passive_target(timeout=0.5)
        if uid is not None:
            print("Found NFC card with UID:", [hex(i) for i in uid])
            time.sleep(1)
    except KeyboardInterrupt:
        GPIO.cleanup()
        break
```

**Comment by siniseong** [comment]
ubuntu@ubuntu:~/home/pi/mywebapp$ sudo python3 hardware.py
Traceback (most recent call last):
  File "/home/ubuntu/home/pi/mywebapp/hardware.py", line 2, in <module>
    from adafruit_pn532 import PN532_SPI
ModuleNotFoundError: No module named 'adafruit_pn532'

**Comment by siniseong** [comment]
ubuntu@ubuntu:~/home/pi/mywebapp$ sudo python3 hardware.py
Traceback (most recent call last):
  File "/home/ubuntu/home/pi/mywebapp/hardware.py", line 2, in <module>
    from adafruit_pn532 import PN532_SPI
ImportError: cannot import name 'PN532_SPI' from 'adafruit_pn532' (/usr/local/lib/python3.10/dist-packages/adafruit_pn532/__init__.py)

**Comment by siniseong** [comment]
import time
import RPi.GPIO as GPIO
from adafruit_pn532 import PN532

GPIO.setmode(GPIO.BCM)

SCK = 11  # BCM 핀 번호 사용
MISO = 9
MOSI = 10
CS = 8

pn532 = PN532(sclk=SCK, mosi=MOSI, miso=MISO, cs=CS, debug=False)

print("Waiting for an NFC card...")

while True:
    try:
        uid = pn532.read_passive_target(timeout=0.5)
        if uid is not None:
            print("Found NFC card with UID:", [hex(i) for i in uid])
            time.sleep(1)
    except KeyboardInterrupt:
        GPIO.cleanup()
        break

**Comment by siniseong** [comment]
File "/home/ubuntu/home/pi/mywebapp/hardware.py", line 17
    try:
    ^
IndentationError: expected an indented block after 'while' statement on line 16

**Comment by siniseong** [comment]
``` import time
import RPi.GPIO as GPIO
from adafruit_pn532 import PN532

GPIO.setmode(GPIO.BCM)

SCK = 11  # BCM 핀 번호 사용
MISO = 9
MOSI = 10
CS = 8

pn532 = PN532(sclk=SCK, mosi=MOSI, miso=MISO, cs=CS, debug=False)

print("Waiting for an NFC card...")

try:
    while True:
        uid = pn532.read_passive_target(timeout=0.5)
        if uid is not None:
            print("Found NFC card with UID:", [hex(i) for i in uid])
            time.sleep(1)
except KeyboardInterrupt:
    GPIO.cleanup()
```

**Comment by siniseong** [comment]
ubuntu@ubuntu:~/home/pi/mywebapp$ sudo python3 hardware.py
Traceback (most recent call last):
  File "/home/ubuntu/home/pi/mywebapp/hardware.py", line 2, in <module>
    from adafruit_pn532 import PN532
ImportError: cannot import name 'PN532' from 'adafruit_pn532' (/usr/local/lib/python3.10/dist-packages/adafruit_pn532/__init__.py)

**Comment by siniseong** [comment]
``` import time
import RPi.GPIO as GPIO
from adafruit_pn532 import PN532_SPI

GPIO.setmode(GPIO.BCM)

SCK = 11  # BCM 핀 번호 사용
MISO = 9
MOSI = 10
CS = 8

pn532 = PN532_SPI(sclk=SCK, mosi=MOSI, miso=MISO, cs=CS, debug=False)

print("Waiting for an NFC card...")

try:
    while True:
        uid = pn532.read_passive_target(timeout=0.5)
        if uid is not None:
            print("Found NFC card with UID:", [hex(i) for i in uid])
            time.sleep(1)
except KeyboardInterrupt:
    GPIO.cleanup()
```

**Comment by siniseong** [comment]
import time
import RPi.GPIO as GPIO
from adafruit_pn532.spi import PN532_SPI

GPIO.setmode(GPIO.BCM)

SCK = 11  # 변경하려는 SCK 핀 번호
MISO = 9  # 변경하려는 MISO 핀 번호
MOSI = 10  # 변경하려는 MOSI 핀 번호
CS = 8  # 변경하려는 CS 핀 번호

pn532 = PN532_SPI(spi_bus=0, spi_device=0, cs=CS, sclk=SCK, miso=MISO, mosi=MOSI, debug=False)

print("Waiting for an NFC card...")

try:
    while True:
        uid = pn532.read_passive_target(timeout=0.5)
        if uid is not None:
            print("Found NFC card with UID:", [hex(i) for i in uid])
            time.sleep(1)
except KeyboardInterrupt:
    GPIO.cleanup()

**Comment by siniseong** [comment]
ubuntu@ubuntu:~/home/pi/mywebapp$ sudo python3 hardware.py
  File "/home/ubuntu/home/pi/mywebapp/hardware.py", line 17
    while True:
    ^
IndentationError: expected an indented block after 'try' statement on line 16

**Comment by siniseong** [comment]
import time
import RPi.GPIO as GPIO
from adafruit_pn532.spi import PN532_SPI

GPIO.setmode(GPIO.BCM)

SCK = 11  # 변경하려는 SCK 핀 번호
MISO = 9  # 변경하려는 MISO 핀 번호
MOSI = 10  # 변경하려는 MOSI 핀 번호
CS = 8  # 변경하려는 CS 핀 번호

pn532 = PN532_SPI(spi_bus=0, spi_device=0, cs=CS, sclk=SCK, miso=MISO, mosi=MOSI, debug=False)

print("Waiting for an NFC card...")

try:
    while True:
        uid = pn532.read_passive_target(timeout=0.5)
        if uid is not None:
            print("Found NFC card with UID:", [hex(i) for i in uid])
            time.sleep(1)
except KeyboardInterrupt:
    GPIO.cleanup()

**Comment by siniseong** [comment]
ubuntu@ubuntu:~/home/pi/mywebapp$ sudo python3 hardware.py
  File "/home/ubuntu/home/pi/mywebapp/hardware.py", line 17
    while True:
    ^
IndentationError: expected an indented block after 'try' statement on line 16

**Comment by siniseong** [comment]
import time
import RPi.GPIO as GPIO
from adafruit_pn532.spi import PN532_SPI

GPIO.setmode(GPIO.BCM)

SCK = 11  # 변경하려는 SCK 핀 번호
MISO = 9  # 변경하려는 MISO 핀 번호
MOSI = 10  # 변경하려는 MOSI 핀 번호
CS = 8  # 변경하려는 CS 핀 번호

pn532 = PN532_SPI(spi_bus=0, spi_device=0, cs=CS, sclk=SCK, miso=MISO, mosi=MOSI, debug=False)

print("Waiting for an NFC card...")

try:
    while True:
        uid = pn532.read_passive_target(timeout=0.5)
        if uid is not None:
            print("Found NFC card with UID:", [hex(i) for i in uid])
            time.sleep(1)
except KeyboardInterrupt:
    GPIO.cleanup()

**Comment by siniseong** [comment]
ubuntu@ubuntu:~/home/pi/mywebapp$ sudo python3 hardware.py
  File "/home/ubuntu/home/pi/mywebapp/hardware.py", line 17
    while True:
    ^
IndentationError: expected an indented block after 'try' statement on line 16

**Comment by siniseong** [comment]
import time
import RPi.GPIO as GPIO
from adafruit_pn532.spi import PN532_SPI

GPIO.setmode(GPIO.BCM)

SCK = 11  # 변경하려는 SCK 핀 번호
MISO = 9  # 변경하려는 MISO 핀 번호
MOSI = 10  # 변경하려는 MOSI 핀 번호
CS = 8  # 변경하려는 CS 핀 번호

pn532 = PN532_SPI(spi_bus=0, spi_device=0, cs=CS, sclk=SCK, miso=MISO, mosi=MOSI, debug=False)

print("Waiting for an NFC card...")

try:
    while True:
        uid = pn532.read_passive_target(timeout=0.5)
        if uid is not None:
            print("Found NFC card with UID:", [hex(i) for i in uid])
            time.sleep(1)
except KeyboardInterrupt:
    GPIO.cleanup()

**Comment by siniseong** [comment]
ubuntu@ubuntu:~/home/pi/mywebapp$ sudo python3 hardware.py
  File "/home/ubuntu/home/pi/mywebapp/hardware.py", line 23
    GPIO.cleanup())
                  ^
SyntaxError: unmatched ')'

**Comment by siniseong** [comment]
import time
import RPi.GPIO as GPIO
from adafruit_pn532.spi import PN532_SPI

GPIO.setmode(GPIO.BCM)

SCK = 11  # 변경하려는 SCK 핀 번호
MISO = 9  # 변경하려는 MISO 핀 번호
MOSI = 10  # 변경하려는 MOSI 핀 번호
CS = 8  # 변경하려는 CS 핀 번호

pn532 = PN532_SPI(spi_bus=0, spi_device=0, cs=CS, sclk=SCK, miso=MISO, mosi=MOSI, debug=False)

print("Waiting for an NFC card...")

try:
    while True:
        uid = pn532.read_passive_target(timeout=0.5)
        if uid is not None:
            print("Found NFC card with UID:", [hex(i) for i in uid])
            time.sleep(1)
except KeyboardInterrupt:
    GPIO.cleanup()

**Comment by siniseong** [comment]
import time
import RPi.GPIO as GPIO
from adafruit_pn532.spi import PN532_SPI

GPIO.setmode(GPIO.BCM)

SCK = 11  # 변경하려는 SCK 핀 번호
MISO = 9  # 변경하려는 MISO 핀 번호
MOSI = 10  # 변경하려는 MOSI 핀 번호
CS = 8  # 변경하려는 CS 핀 번호

pn532 = PN532_SPI(spi_bus=0, spi_device=0, cs=CS, sclk=SCK, miso=MISO, mosi=MOSI, debug=False)

print("Waiting for an NFC card...")

try:
    while True:
        uid = pn532.read_passive_target(timeout=0.5)
        if uid is not None:
            print("Found NFC card with UID:", [hex(i) for i in uid])
            time.sleep(1)
except KeyboardInterrupt:
    GPIO.cleanup()
